### ISSUE TITLE
some tests may fail if BSP has non-zero lapic_id

### ISSUE THREAD

**Issue by dmitry-bluerock** [cyberus-technology/guest-tests#1]
`lapic_test_tools::send_self_ipi()` for case with no shortcut incorrectly shifts `apic_id`. However it's only visible if `apic_id` is not zero.

`ICR_DEST_SHIFT` seems to be defined for case with low/high parts {56-32}. While here `icr_entry` is a full 64-bit type/value.

possible patch would be:

```
--- a/src/lib/toyos/src/testhelper/lapic_test_tools.cpp
+++ b/src/lib/toyos/src/testhelper/lapic_test_tools.cpp
@@ -288,8 +288,8 @@ void lapic_test_tools::send_self_ipi(uint8_t vector, dest_sh sh, dest_mode dest,
     icr_entry |= sh << ICR_DEST_SH_SHIFT;
 
     if (sh == dest_sh::NO_SH) {
-        uint32_t apic_id = (read_from_register(LAPIC_ID) >> LAPIC_ID_SHIFT) & LAPIC_ID_MASK;
-        icr_entry |= apic_id << ICR_DEST_SHIFT;
+        uint64_t apic_id = (read_from_register(LAPIC_ID) >> LAPIC_ID_SHIFT) & LAPIC_ID_MASK;
+        icr_entry |= apic_id << 56;
     }
 
     icr_entry |= vector;
```

**Comment by tpressure** [comment]
You are absolutely right. Thanks for reporting this.

**Comment by phip1611** [comment]
Thanks a lot for pointing that out! Fixed with https://github.com/cyberus-technology/guest-tests/commit/a3ba281ce078e5adbe2db3a82b3d859b9ef2c92c
